[package]
name = "json-rs"
version = "0.0.1"
build = "build.rs"

[dependencies]
serde = "0.8"
serde_json = "0.8"

[build-dependencies]
serde_codegen = "0.8"

[profile.release]
lto = true

[[bin]]
name = "json-value-rs"
path = "src/json_value.rs"

[[bin]]
name = "json-struct-rs"
path = "src/json_struct.rs"

[[bin]]
name = "json-pull-rs"
path = "src/json_pull.rs"
